global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'kv-node1'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['node1:8080']
  - job_name: 'kv-node2'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['node2:8081']
  - job_name: 'kv-node3'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['node3:8082']
