apiVersion: v1
kind: Service
metadata:
  name: node3
  namespace: kv-store
spec:
  type: ClusterIP
  selector:
    app: kv-node
    node: node3
  ports:
    - name: http
      port: 8082
      targetPort: 8082
    - name: grpc
      port: 9092
      targetPort: 9092

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kv-node3
  namespace: kv-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kv-node
      node: node3
  template:
    metadata:
      labels:
        app: kv-node
        node: node3
    spec:
      containers:
        - name: kv-node3
          image: kv-store:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
            - containerPort: 9092
          env:
            - name: NODE_ID
              value: "node3"
            - name: SERVER_PORT
              value: "8082"
            - name: GRPC_PORT
              value: "9092"
            - name: DATA_DIR
              value: /data/node3
            - name: PEERS
              value: "node1:node1:9090,node2:node2:9091"
          readinessProbe:
            httpGet:
              path: /admin/status
              port: 8082
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /admin/status
              port: 8082
            initialDelaySeconds: 40
            periodSeconds: 15
            failureThreshold: 3
          volumeMounts:
            - name: data
              mountPath: /data/node3
      volumes:
        - name: data
          emptyDir: {}
